apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-recreate
  labels:
    app: spring-petclinic-recreate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic-recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-petclinic-recreate
    spec:
      containers:
      - name: spring-petclinic-rest-container
        image: docker.io/springcommunity/spring-petclinic-rest:3.0.2
        ports:
        - containerPort: 9966