apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-27T14:36:32Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "6885"
  uid: 3b701312-b12d-40d0-a9ab-ea6af8754e1c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.24.162
  clusterIPs:
  - 10.97.24.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31212
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
